// --- CITIES DATA --- (No changes needed here from the previous version)
const CITIES = [
    { id: 'tokyo', name: 'Tokyo', country: 'Japan', description_corta: 'The bustling capital of Japan.', description_long: 'Neon lights illuminate towering skyscrapers while ancient temples offer moments of peace...', investigation_options: [ { name: 'Check Airport Departures', focus: 'destination' }, { name: 'Talk to Electronics Dealer', focus: 'identity' }, { name: 'Visit Senso-ji Temple', focus: 'mixed' } ], possible_clues: ['clue_dest_paris', 'clue_id_male', 'clue_id_hobby_electronics', 'clue_id_vehicle_sportscar', 'clue_id_hair_black', 'clue_id_accessory_glasses'] },
    { id: 'paris', name: 'Paris', country: 'France', description_corta: 'The city of love and lights.', description_long: 'Iconic landmarks grace the skyline, from the Eiffel Tower to Notre Dame...', investigation_options: [ { name: 'Inquire at the Louvre', focus: 'identity' }, { name: 'Question Hotel Concierge', focus: 'destination' }, { name: 'Search Latin Quarter Cafe', focus: 'mixed' } ], possible_clues: ['clue_dest_cairo', 'clue_id_female', 'clue_id_hair_brown', 'clue_id_vehicle_limo', 'clue_id_hobby_art', 'clue_id_accessory_necklace'] },
    { id: 'cairo', name: 'Cairo', country: 'Egypt', description_corta: 'Ancient city on the Nile.', description_long: 'A chaotic yet captivating metropolis where millennia of history meet modern life...', investigation_options: [ { name: 'Consult Museum Curator', focus: 'identity' }, { name: 'Explore Khan el-Khalili', focus: 'mixed' }, { name: 'Check Nile Cruise Bookings', focus: 'destination' } ], possible_clues: ['clue_dest_rome', 'clue_id_hobby_archeology', 'clue_id_accessory_scarf', 'clue_id_male', 'clue_id_hair_red'] },
    { id: 'rome', name: 'Rome', country: 'Italy', description_corta: 'The Eternal City, full of history.', description_long: 'Ruins of a vast empire stand beside Renaissance masterpieces...', investigation_options: [ { name: 'Examine Colosseum Entry Logs', focus: 'mixed' }, { name: 'Talk to Local Restaurateur', focus: 'identity' }, { name: 'Check Train Station Schedule', focus: 'destination' } ], possible_clues: ['clue_dest_moscow', 'clue_id_hair_black', 'clue_id_vehicle_scooter', 'clue_id_female', 'clue_id_hobby_art'] },
    { id: 'moscow', name: 'Moscow', country: 'Russia', description_corta: 'Russian capital with its Red Square.', description_long: 'Grandeur defines Moscow, from the onion domes of St. Basil\'s to the imposing Kremlin walls...', investigation_options: [ { name: 'Investigate Bolshoi Theater', focus: 'identity' }, { name: 'Check Kremlin Visitor Records', focus: 'mixed' }, { name: 'Inquire at Intourist Office', focus: 'destination' } ], possible_clues: ['clue_dest_london', 'clue_id_hobby_chess', 'clue_id_accessory_hat', 'clue_id_male', 'clue_id_hair_gray'] },
    { id: 'london', name: 'London', country: 'UK', description_corta: 'Global financial and cultural center.', description_long: 'A diverse and dynamic city where royal tradition meets cutting-edge trends...', investigation_options: [ { name: 'Speak with Museum Security', focus: 'identity' }, { name: 'Visit Scotland Yard (Info Desk)', focus: 'mixed' }, { name: 'Check Heathrow Departures', focus: 'destination' } ], possible_clues: ['clue_dest_rio', 'clue_id_female', 'clue_id_hair_blonde', 'clue_id_vehicle_taxi', 'clue_id_accessory_necklace'] },
    { id: 'rio', name: 'Rio de Janeiro', country: 'Brazil', description_corta: 'Famous for its beaches and carnival.', description_long: 'Dramatic mountains plunge into sparkling bays...', investigation_options: [ { name: 'Talk to Beach Vendor', focus: 'mixed' }, { name: 'Inquire at Samba School', focus: 'identity' }, { name: 'Check Galeão Airport Flights', focus: 'destination' } ], possible_clues: ['clue_dest_sydney', 'clue_id_male', 'clue_id_hobby_music', 'clue_id_accessory_ring', 'clue_id_vehicle_convertible'] },
    { id: 'sydney', name: 'Sydney', country: 'Australia', description_corta: 'Known for its Opera House and bridge.', description_long: 'A stunning harbor city with iconic architecture...', investigation_options: [ { name: 'Question Opera House Staff', focus: 'mixed' }, { name: 'Check Bondi Beach Lifeguard Log', focus: 'identity' }, { name: 'Look into International Flights', focus: 'destination' } ], possible_clues: ['clue_dest_bangkok', 'clue_id_hair_red', 'clue_id_vehicle_convertible', 'clue_id_female', 'clue_id_accessory_backpack'] },
    { id: 'bangkok', name: 'Bangkok', country: 'Thailand', description_corta: 'Vibrant Thai capital with ornate temples.', description_long: 'Ornate shrines stand beside bustling markets and modern malls...', investigation_options: [ { name: 'Talk to Tuk-Tuk Driver', focus: 'destination' }, { name: 'Investigate Grand Palace Area', focus: 'mixed' }, { name: 'Visit Tourist Information Center', focus: 'identity' } ], possible_clues: ['clue_dest_mexico', 'clue_id_accessory_glasses', 'clue_id_male', 'clue_id_hobby_photography', 'clue_id_hair_gray'] },
    { id: 'mexico', name: 'Mexico City', country: 'Mexico', description_corta: 'Historic capital built on ancient ruins.', description_long: 'A sprawling metropolis rich in Aztec history and colonial architecture...', investigation_options: [ { name: 'Inquire at Anthropology Museum', focus: 'identity' }, { name: 'Check Zocalo Security Feed', focus: 'vehicle' }, { name: 'Ask Street Vendor near Palacio Nacional', focus: 'mixed' } ], possible_clues: ['clue_id_vehicle_sedan', 'clue_id_female', 'clue_id_hair_black', 'clue_id_hobby_art'] }
];

// --- THIEVES DATA --- (Same as before)
const THIEVES = [
    { id: 'carmen', name: 'Carmen Sandiego', gender: 'Female', hobby: 'Geography', hair_color: 'Brown', accessory: 'Hat', vehicle: 'Private Jet' },
    { id: 'nick', name: 'Nick Brunch', gender: 'Male', hobby: 'Electronics', hair_color: 'Black', accessory: 'Glasses', vehicle: 'Sports Car' },
    { id: 'contessa', name: 'The Contessa', gender: 'Female', hobby: 'Art', hair_color: 'Blonde', accessory: 'Necklace', vehicle: 'Limousine' },
    { id: 'rock', name: 'Rock Solid', gender: 'Male', hobby: 'Climbing', hair_color: 'Red', accessory: 'Backpack', vehicle: 'Off-road Vehicle' },
    { id: 'silas', name: 'Silas Sterling', gender: 'Male', hobby: 'Photography', hair_color: 'Gray', accessory: 'Watch', vehicle: 'Sedan' }
];

// --- CLUES DATA --- (Added riddle_text)
const CLUES = [
    // Destination Clues
    { id: 'clue_dest_paris', text_pista: 'Changed currency to Euros.', witness_statement: 'A travel agent mentioned someone booked a one-way flight to Charles de Gaulle, asking about museum hours.', riddle_text: 'They mentioned wanting to see a famous tower sparkle at night, in the City of Love.', type: 'destination', value_associated: 'paris' },
    { id: 'clue_dest_cairo', text_pista: 'They bought a book on Egyptian hieroglyphs.', witness_statement: 'Overheard them talking about wanting to see the Sphinx up close.', riddle_text: 'The suspect spoke of ancient pharaohs and a journey down the longest river.', type: 'destination', value_associated: 'cairo' },
    { id: 'clue_dest_rome', text_pista: 'Was humming an aria from a famous opera.', witness_statement: 'They asked a local where the best gelato near the ancient ruins was.', riddle_text: 'Said they were heading where all roads lead, to toss a coin in a famous fountain.', type: 'destination', value_associated: 'rome' },
    { id: 'clue_dest_moscow', text_pista: 'Carried a Russian phrasebook.', witness_statement: 'Someone fitting their description was seen buying tickets for the ballet.', riddle_text: 'Packed for the cold, they mentioned visiting a square known for its colorful onion domes.', type: 'destination', value_associated: 'moscow' },
    { id: 'clue_dest_london', text_pista: 'Packed an umbrella despite the clear sky.', witness_statement: 'They specifically asked about flights arriving at Heathrow airport.', riddle_text: 'The target was interested in seeing where royalty lives and hearing Big Ben chime.', type: 'destination', value_associated: 'london' },
    { id: 'clue_dest_rio', text_pista: 'Bought a Portuguese dictionary.', witness_statement: 'Booked a hotel near Copacabana, bragging about the view.', riddle_text: 'They were looking for rhythm and sun, perhaps near a giant statue overlooking a bay.', type: 'destination', value_associated: 'rio' },
    { id: 'clue_dest_sydney', text_pista: 'Mentioned wanting to go scuba diving.', witness_statement: 'They were looking at brochures for surfing lessons down under.', riddle_text: 'Destination hint: They asked about the weather down under, near a famous sail-shaped building.', type: 'destination', value_associated: 'sydney' },
    { id: 'clue_dest_bangkok', text_pista: 'Exchanged currency for Thai Baht.', witness_statement: 'Asked about the best way to travel via longtail boat on the river.', riddle_text: 'Wanted to see floating markets and golden temples in the "Land of Smiles".', type: 'destination', value_associated: 'bangkok' },
    { id: 'clue_dest_mexico', text_pista: 'Bought a Spanish phrasebook.', witness_statement: 'Was overheard arranging transport to see ancient Aztec sites.', riddle_text: 'Packed for altitude, mentioning a desire to explore ancient ruins in a vast, historic capital.', type: 'destination', value_associated: 'mexico' },

    // Identity Clues (Same as before, witness statements provide hints)
    { id: 'clue_id_female', text_pista: 'The suspect wore perfume.', witness_statement: 'The getaway driver referred to the boss as "she".', type: 'identity', value_associated: { property: 'gender', value: 'Female' } },
    { id: 'clue_id_male', text_pista: 'Left behind a men\'s glove.', witness_statement: 'I distinctly remember a deep voice giving orders.', type: 'identity', value_associated: { property: 'gender', value: 'Male' } },
    // ... (rest of the identity clues are the same as the previous version) ...
    { id: 'clue_id_hobby_electronics', text_pista: 'Disabled the alarm with unusual skill.', witness_statement: 'They were carrying a bag full of wires and strange devices.', type: 'identity', value_associated: { property: 'hobby', value: 'Electronics' } },
    { id: 'clue_id_hobby_archeology', text_pista: 'Left behind fine grains of sand and pottery dust.', witness_statement: 'Seemed more interested in the museum\'s historical artifacts than the exhibits.', type: 'identity', value_associated: { property: 'hobby', value: 'Archeology' } },
    { id: 'clue_id_hobby_chess', text_pista: 'Made a calculated, precise escape.', witness_statement: 'Someone saw them playing chess in the park earlier, winning quickly.', type: 'identity', value_associated: { property: 'hobby', value: 'Chess' } },
    { id: 'clue_id_hobby_music', text_pista: 'Tapped out a complex rhythm on the counter.', witness_statement: 'Mentioned needing to get back for band practice.', type: 'identity', value_associated: { property: 'hobby', value: 'Music' } },
    { id: 'clue_id_hobby_photography', text_pista: 'A discarded lens cap was found.', witness_statement: 'They were seen taking photos of the escape route before the heist.', type: 'identity', value_associated: { property: 'hobby', value: 'Photography' } },
    { id: 'clue_id_hobby_geography', text_pista: 'Navigated the city like a local.', witness_statement: 'Corrected the tour guide about a geographical fact.', type: 'identity', value_associated: { property: 'hobby', value: 'Geography' } },
    { id: 'clue_id_hobby_art', text_pista: 'Studied the stolen item with an expert eye.', witness_statement: 'Discussed painting techniques with the gallery owner.', type: 'identity', value_associated: { property: 'hobby', value: 'Art' } },
    { id: 'clue_id_hobby_climbing', text_pista: 'Scaled the wall with surprising agility.', witness_statement: 'Complained about the lack of good climbing spots nearby.', type: 'identity', value_associated: { property: 'hobby', value: 'Climbing' } },
    { id: 'clue_id_hair_brown', text_pista: 'A witness described chestnut-colored hair.', witness_statement: 'They had rich, brown hair tied back neatly.', type: 'identity', value_associated: { property: 'hair_color', value: 'Brown' } },
    { id: 'clue_id_hair_black', text_pista: 'Security footage showed very dark hair.', witness_statement: 'Ink-black hair, cut short and sharp.', type: 'identity', value_associated: { property: 'hair_color', value: 'Black' } },
    { id: 'clue_id_hair_blonde', text_pista: 'A few strands of golden hair were found.', witness_statement: 'Definitely blonde, and very well styled.', type: 'identity', value_associated: { property: 'hair_color', value: 'Blonde' } },
    { id: 'clue_id_hair_red', text_pista: 'Witness mentioned hair the color of fire.', witness_statement: 'That bright red hair was hard to miss.', type: 'identity', value_associated: { property: 'hair_color', value: 'Red' } },
    { id: 'clue_id_hair_gray', text_pista: 'Had salt-and-pepper or gray hair.', witness_statement: 'Looked sophisticated with their gray hair.', type: 'identity', value_associated: { property: 'hair_color', value: 'Gray' } },
    { id: 'clue_id_accessory_scarf', text_pista: 'Wore a silk scarf.', witness_statement: 'Even indoors, they kept the stylish scarf on.', type: 'identity', value_associated: { property: 'accessory', value: 'Scarf' } },
    { id: 'clue_id_accessory_hat', text_pista: 'Sported a wide-brimmed hat.', witness_statement: 'Almost couldn\'t see their face under that hat.', type: 'identity', value_associated: { property: 'accessory', value: 'Hat' } },
    { id: 'clue_id_accessory_ring', text_pista: 'Flashed a large signet ring.', witness_statement: 'Saw a glint of gold from a ring on their finger.', type: 'identity', value_associated: { property: 'accessory', value: 'Ring' } },
    { id: 'clue_id_accessory_glasses', text_pista: 'Wore thick-rimmed glasses.', witness_statement: 'Adjusted their glasses frequently while examining the loot.', type: 'identity', value_associated: { property: 'accessory', value: 'Glasses' } },
    { id: 'clue_id_accessory_necklace', text_pista: 'Adorned with a string of pearls.', witness_statement: 'The necklace looked like it was worth a fortune itself!', type: 'identity', value_associated: { property: 'accessory', value: 'Necklace' } },
    { id: 'clue_id_accessory_backpack', text_pista: 'Carried a worn leather backpack.', witness_statement: 'Looked like they were ready for a hike, not a heist.', type: 'identity', value_associated: { property: 'accessory', value: 'Backpack' } },
    { id: 'clue_id_accessory_watch', text_pista: 'Checked a complicated-looking watch.', witness_statement: 'The watch face had multiple dials, looked expensive.', type: 'identity', value_associated: { property: 'accessory', value: 'Watch' } },
    { id: 'clue_id_vehicle_limo', text_pista: 'Escaped in a chauffeur-driven limousine.', witness_statement: 'Black stretch limo, tinted windows, very suspicious.', type: 'identity', value_associated: { property: 'vehicle', value: 'Limousine' } },
    { id: 'clue_id_vehicle_scooter', text_pista: 'A scooter was seen speeding away.', witness_statement: 'Heard a whining noise, then saw a scooter zip past.', type: 'identity', value_associated: { property: 'vehicle', value: 'Scooter' } },
    { id: 'clue_id_vehicle_taxi', text_pista: 'Jumped into a waiting taxi.', witness_statement: 'The taxi didn\'t even stop fully, just slowed down for them.', type: 'identity', value_associated: { property: 'vehicle', value: 'Taxi' } },
    { id: 'clue_id_vehicle_convertible', text_pista: 'Fled in a convertible, top down.', witness_statement: 'That car was too flashy for this neighborhood.', type: 'identity', value_associated: { property: 'vehicle', value: 'Convertible' } },
    { id: 'clue_id_vehicle_jet', text_pista: 'An unscheduled private jet took off.', witness_statement: 'Air traffic control confirmed a small jet departed right after the alarm.', type: 'identity', value_associated: { property: 'vehicle', value: 'Private Jet' } },
    { id: 'clue_id_vehicle_sportscar', text_pista: 'Tire marks indicate a high-performance sports car.', witness_statement: 'Heard squealing tires and saw a red blur.', type: 'identity', value_associated: { property: 'vehicle', value: 'Sports Car' } },
    { id: 'clue_id_vehicle_offroad', text_pista: 'Left muddy tracks from an off-road vehicle.', witness_statement: 'No ordinary car could have gone through that alley.', type: 'identity', value_associated: { property: 'vehicle', value: 'Off-road Vehicle' } },
    { id: 'clue_id_vehicle_sedan', text_pista: 'A dark sedan was parked nearby.', witness_statement: 'It looked like any other car, blended right in.', type: 'identity', value_associated: { property: 'vehicle', value: 'Sedan' } }
];

// --- CASES DATA --- (Same as before)
const CASES = [
    { id: 'case001', objeto_robado: 'The Eye of the Serpent Ruby', ciudad_inicial_id: 'cairo', ladrón_asignado_id: 'nick', ruta_escape: ['cairo', 'rome', 'paris', 'london'] },
    { id: 'case002', objeto_robado: 'The Star of Rio Diamond', ciudad_inicial_id: 'rio', ladrón_asignado_id: 'contessa', ruta_escape: ['rio', 'london', 'moscow', 'tokyo'] },
    { id: 'case003', objeto_robado: 'The Golden Buddha of Ayutthaya', ciudad_inicial_id: 'bangkok', ladrón_asignado_id: 'silas', ruta_escape: ['bangkok', 'sydney', 'mexico'] }
];

// --- Helper Functions for Data --- (Same as before)
function findCityById(id) { return CITIES.find(city => city.id === id); }
function findThiefById(id) { return THIEVES.find(thief => thief.id === id); }
function findClueById(id) { return CLUES.find(clue => clue.id === id); }
function getUniqueThiefProperties(property) { /* ... same ... */
    const values = new Set();
    THIEVES.forEach(thief => {
        if (thief[property]) { values.add(thief[property]); }
    });
    return Array.from(values).sort();
 }